### PR TITLE
Add progress indicator to get_valid_segments(segments)

### PR DESCRIPTION
**Pull request by Glyx**
Hello !

I was checking the segments for a *really* long VOD ([here](https://dgeft87wbj63p.cloudfront.net/4052cd64a7a5e021cad6_lestream_46056607308_1663053064/chunked/index-dvr.m3u8)) and even though it's not a vital feature, I was a bit frustrated with not being able to know when it would finish.

So I thought it would be cool to have a way of seeing the progress of the process.

### CODE REVIEW

**Comment by Glyx** [comment]
The expected behavior is that it should be printing the segment no. being checked along with a progress percentage.

I tested this by cloning my forked repository on multiple systems (Python 3.11 on Windows 11 64bit ([video](https://streamable.com/qa663j)), Python 3.10.6 on Ubuntu 22.04.1 on WSL2 ([video](https://streamable.com/1w5hp8)) and Arm 64bit ([video](https://streamable.com/kpmqg1))) and everything works as intended so that's weird...

P.S. : maybe I'm misunderstanding and you do not deem the feature worthwhile, which I can understand. In any case, sorry for the inconvenience.

**Comment by ItIckeYd** [comment]
@Glyx hmm.. I seen your video. That’s interesting there is no progression when I do it.. in pycharm it only shows when the segment check is 100% complete. 

I’ll have to look into it further.

**Comment by Glyx** [comment]
I modified my code to take into account PyCharm not supporting `print()` parameter `end='\r'`.

**Review by ItIckeYd — APPROVED** [review]
@Glyx Works after the change... thank you. Merging into main branch.

**Pull request merged**
